# Generated by Django 2.2.4 on 2019-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfeature',
            name='remote_url',
        ),
        migrations.AddField(
            model_name='textfeature',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
