# Generated by Django 2.2.4 on 2019-08-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_auto_20190815_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='TextLabel',
            fields=[
                ('label_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_model.Label')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('exclusive', 'exclusive'), ('multiple', 'multiple')], default='exclusive', max_length=64)),
            ],
            bases=('data_model.label',),
        ),
    ]
