# Generated by Django 2.2.4 on 2019-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0003_label_textlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlabel',
            name='group',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
