# Generated by Django 2.2.4 on 2019-08-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0004_textlabel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_model.Annotation'),
        ),
    ]
