# Generated by Django 2.2.4 on 2019-08-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0005_auto_20190815_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='example',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_model.Example'),
            preserve_default=False,
        ),
    ]
