# Generated by Django 2.2.4 on 2019-08-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0008_auto_20190816_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='data_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_model.DataSource'),
            preserve_default=False,
        ),
    ]
