# Generated by Django 2.2.4 on 2019-08-16 14:54

import data_model.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0009_example_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=data_model.models.meta_default),
        ),
    ]
