# Generated by Django 2.2.4 on 2019-08-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0010_example_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
