# Generated by Django 2.2.4 on 2019-08-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0012_auto_20190816_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='textlabel',
            name='label_ptr',
        ),
        migrations.RemoveField(
            model_name='example',
            name='meta',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='TextLabel',
        ),
        migrations.AddField(
            model_name='stringtag',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Example'),
        ),
    ]
