# Generated by Django 2.2.4 on 2019-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0013_auto_20190819_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringtag',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stringtag',
            name='value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='stringtag',
            unique_together={('example', 'key')},
        ),
    ]
