# Generated by Django 2.2.4 on 2019-08-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0019_annotation_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stringtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stringtag',
            name='example',
        ),
    ]
