# Generated by Django 2.2.4 on 2019-08-19 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0020_auto_20190819_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stringtag',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
