# Generated by Django 2.2.4 on 2019-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0022_auto_20190819_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='tags',
            field=models.ManyToManyField(through='data_model.Annotation', to='data_model.StringTag'),
        ),
    ]
