# Generated by Django 2.2.4 on 2019-08-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0023_example_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='data_model.Example'),
        ),
    ]
